---
title: Noday
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: info@keiyasui.com
description: |
  Noday website
baseurl: ''
url: http://example.com
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
theme: minima
