---
title: Noday
timezone: UTC
collections:
  uploads:
    title: Uploads
    output: true
  case-study:
    title: case-studies
    output: true
defaults:
  -
    scope:
      path: ""
      type: "case-study"
    values:
      layout: "case-study-single"
      Logo: 
        logo-image: ""
      Short Description: ""
      Content:
        - Title: ""
          Paragraph: ""
email: info@keiyasui.com
description: |
  Noday website
exclude:
- node_modules
- package.json
- gulpfile.js
- ".git"
- ".sass-cache"
- Gemfile
- Gemfile.lock
- feed.xml
url: http://keiyasui.com

twitter_username: keiyasui
github_username: kyasui
markdown: kramdown
