---
title: Noday
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  case-study:
    title: case-studies
    output: true
defaults:
- scope:
    path: ''
    type: case-study
  values:
    layout: case-study-single
    Logo:
      logo-image: ''
    Short Description: ''
    Content:
    - Title: ''
      Paragraph: ''
email: info@keiyasui.com
description: 'Noday website

'
exclude:
- node_modules
- package.json
- gulpfile.js
- ".git"
- ".sass-cache"
- Gemfile
- Gemfile.lock
- feed.xml
url: http://www.noday.co
twitter_username: nodayresearch
github_username: kyasui
markdown: kramdown
gems:
- jekyll-sitemap
